In [1]:
print("DD")

DD


In [23]:
import numpy
import scipy.special

class NeuralNetwork:
    
    #神经网络类的初始化方法
    def __init__(self,inputnodes,hiddennodes,outputnodes,learningrate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        self.lr = learningrate
        
        #输入层和隐藏层的链接权重矩阵（self.hnodes,self.inodes）
        self.weight_h = numpy.random.normal(0.0,pow(self.hnodes,-0.5),(self.hnodes,self.inodes))    
        
        #隐藏层和输出层的链接权重矩阵（self.onodes,self.hnodes）
        self.weight_o = numpy.random.normal(0.0,pow(self.onodes,-0.5),(self.onodes,self.hnodes))    
        
        #S型激活函数
        self.activation_function = lambda x:scipy.special.expit(x)
        pass
    
    #训练
    def __train__(self,input_list,target_list):
        inputs = numpy.array(input_list, ndmin = 2).T
        targets = numpy.array(target_list, ndmin = 2).T
        
        hide_inputs = numpy.dot(inputs,self.weight_h)
        hide_outputs = self.activation_function(hide_inputs)
        
        final_inputs = numpy.dot(hide_outputs,self.weight_o)
        final_outputs = self.activation_function(final_inputs)
        
        output_errors = targets - final_outputs
        hide_errors = numpy.dot(self.weight_o.T,output_errors)
        
        self.weight_o = self.lr * numpy.dot((output_errors * final_outputs * (1 - final_outputs)),numpy.transpose(hide_outputs))
        self.weight_h = self.lr * numpy.dot((hide_errors * hide_outputs * (1 - hide_outputs)),numpy.transpose(inputs))
                                            
        pass
    
    #查询
    def __query__(self,input_list):        
        inputs = numpy.array(input_list, ndmin = 2).T
        
        hide_inputs = numpy.dot(inputs,self.weight_h)
        hide_outputs = self.activation_function(hide_inputs)
        
        final_inputs = numpy.dot(hide_outputs,self.weight_o)
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
        pass   
    pass

def doubleSize(array):
    doubleSizeArray = numpy.zeros([3,3])
    for i in range(3):
        for j in range(3):
            doubleSizeArray[i,j] = array[i,j] * 2
            pass
        pass
    
    return doubleSizeArray
pass
    

input_nodes = 3
hidden_nodes = 3
output_nodes = 3

learning_rate = 0.5

n = NeuralNetwork(input_nodes,hidden_nodes,output_nodes,learning_rate)

a = numpy.zeros([3,3])

b = numpy.zeros([3,3])

for i in range(3):
    for j in range(3):
        a[i,j] = i + j
        pass
    pass

for i in range(3):
    for j in range(3):
        b[i,j] = a[i,j] * 2
        pass
    pass

la = list(range(1000))
lb = list(range(1000))

la[0] = a
lb[0] = b

count = 1
while(count < 1000):
    la[count] = doubleSize(a)
    lb[count] = doubleSize(la[count])
    count += 1

print(a)
print(b)

print(n.__query__(a))

count = 0
while (count < 1000):
    n.__train__(la[count],lb[count])
    count += 1

print(n.__query__(a))

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
[[0. 2. 4.]
 [2. 4. 6.]
 [4. 6. 8.]]
[[0.3973768  0.4010486  0.54392435]
 [0.39550006 0.38704398 0.56932031]
 [0.39125046 0.37851107 0.58623772]]
[[0.56174626 0.56174626 0.56174626]
 [0.56174626 0.56174626 0.56174626]
 [0.56174626 0.56174626 0.56174626]]


In [108]:
import numpy
import matplotlib.pyplot
%matplotlib inline
import scipy.special
import imageio

class NeuralNetwork:
    
    #神经网络类的初始化方法
    def __init__(self,inputnodes,hiddennodes,outputnodes,learningrate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        self.lr = learningrate
        
        #输入层和隐藏层的链接权重矩阵（self.hnodes,self.inodes）
        self.weight_h = numpy.random.normal(0.0,pow(self.hnodes,-0.5),(self.hnodes,self.inodes))    
        
        #隐藏层和输出层的链接权重矩阵（self.onodes,self.hnodes）
        self.weight_o = numpy.random.normal(0.0,pow(self.onodes,-0.5),(self.onodes,self.hnodes))    
        
        #S型激活函数
        self.activation_function = lambda x:scipy.special.expit(x)
        pass
    
    #训练
    def __train__(self,input_list,target_list):
        inputs = numpy.array(input_list, ndmin = 2).T
        targets = numpy.array(target_list, ndmin = 2).T
        
        hide_inputs = numpy.dot(self.weight_h,inputs)
        hide_outputs = self.activation_function(hide_inputs)
        
        final_inputs = numpy.dot(self.weight_o,hide_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        output_errors = targets - final_outputs
        hide_errors = numpy.dot(self.weight_o.T,output_errors)
        
        self.weight_o += self.lr * numpy.dot((output_errors * final_outputs * (1 - final_outputs)),numpy.transpose(hide_outputs))
        self.weight_h += self.lr * numpy.dot((hide_errors * hide_outputs * (1 - hide_outputs)),numpy.transpose(inputs))
                                            
        pass
    
    #查询
    def __query__(self,input_list):        
        inputs = numpy.array(input_list, ndmin = 2).T
        
        hide_inputs = numpy.dot(self.weight_h,inputs)
        hide_outputs = self.activation_function(hide_inputs)
        
        final_inputs = numpy.dot(self.weight_o,hide_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
        pass   
    pass


input_nodes = 784
hidden_nodes = 100
output_nodes = 10

learning_rate = 0.3

m = NeuralNetwork(input_nodes,hidden_nodes,output_nodes,learning_rate)

dataFiles = open("mnist_dataset/mnist_train.csv",'r')

dataList = dataFiles.readlines()

dataFiles.close()

print(len(dataList))

for data in dataList:
    value = data.split(',')
    inputs = (numpy.asfarray(value[1:])/255.0*0.99)+0.01
    
    onodes = 10
    targets = numpy.zeros(onodes) + 0.01
    targets[int(value[0])] = 0.99
    
    m.__train__(inputs,targets)
    pass

testFiles = open("mnist_dataset/100_mnist_train.csv",'r')

testList = testFiles.readlines()

testFiles.close()

print(len(testList))

scorecard = []

# go through all the records in the test data set
for record in testList:
    # split the record by the ',' commas
    all_values = record.split(',')
    # correct answer is first value
    correct_label = int(all_values[0])
    #print(correct_label, "correct label")
    # scale and shift the inputs
    inputs = (numpy.asfarray(all_values[1:]) / 255.0 * 0.99) + 0.01
    # query the network
    outputs = m.__query__(inputs)
    # the index of the highest value corresponds to the label
    label = numpy.argmax(outputs)
    #print(label, "network's answer")
    #print()
    # append correct or incorrect to list
    if (label == correct_label):
        # network's answer matches correct answer, add 1 to scorecard
        scorecard.append(1)
    else:
        # network's answer doesn't match correct answer, add 0 to scorecard
        scorecard.append(0)
        pass    
    pass

image_file_name = "my_own_images/2828_my_own_2.png"
img_array = scipy.misc.imread(image_file_name,flatten = True)
img_data = 255.0 - img_array . reshape(784)
img_data = (img_data / 255.0 * 0.99 ) + 0.01
print(numpy.argmax(m.__query__(img_data)))

# calculate the performance score, the fraction of correct answers
scorecard_array = numpy.asarray(scorecard)
print ("performance = ", scorecard_array.sum() / scorecard_array.size)

60000
100
2
performance =  0.96


/home/dongdi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:124: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
