In [14]:
import numpy

a = numpy.zeros([3,4])

print(a,"\n")

print(a.shape,"\n")

row,col = a.shape

print("row =",row,"col =",col)

print("shape[0] =",a.shape[0],"shape[1] =",a.shape[1])

w = numpy.random.randn(2, 3, 4, 4)
print(w)

b = numpy.zeros((5))
b

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

(3, 4) 

row = 3 col = 4
shape[0] = 3 shape[1] = 4
[[[[ 0.01934916  1.16964457 -0.12641675 -0.30521011]
   [ 0.85746192  0.31243334  0.06193005 -0.42120835]
   [ 0.21155033  0.21362612  0.47829532  0.84257123]
   [ 1.18700651  0.56728765  0.11336449  0.86058553]]

  [[ 0.10120195  0.38176916  1.58339378 -0.48825006]
   [-0.91004872 -0.45102704 -1.07331661  0.57775667]
   [-2.17895603  0.78644226 -1.4154201  -1.07915503]
   [ 0.58948573  0.701732   -1.00357428 -0.09790773]]

  [[-0.60860248 -1.16823226  1.61854717 -0.24747044]
   [-1.37311872 -0.21058601 -3.472357    0.16171962]
   [ 1.68405396 -0.06280825  0.1300595  -0.41751964]
   [-0.67095092 -1.2471824   2.28075191  1.13906671]]]


 [[[ 0.65715338 -0.20700326 -0.19220332  0.09660482]
   [-0.91937318 -0.63076721  1.86636081 -0.52694989]
   [-0.40264738  0.19777289 -1.04258101 -0.08794426]
   [ 1.45938549 -1.73292748  1.95841546 -0.34999321]]

  [[ 2.11306414 -0.5999674   1.99127484 -0.

array([0., 0., 0., 0., 0.])

In [20]:
def conv2(X, k): 
    x_row, x_col = X.shape 
    k_row, k_col = k.shape 
    ret_row, ret_col = x_row - k_row + 1, x_col - k_col + 1 
    ret = numpy.empty((ret_row, ret_col)) 
    for y in range(ret_row): 
        for x in range(ret_col): 
            sub = X[y : y + k_row, x : x + k_col] 
            ret[y,x] = numpy.sum(sub * k) 
    return ret

a = numpy.zeros([5,5])

b = numpy.zeros([3,3])

print(conv2(a,b))

c = numpy.zeros((3))

print(conv2(a,b)+c)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
a = numpy.zeros([3,3])

a[0,0] = 1
a[2,1] = 2

print(a)
print(numpy.argmax(a))

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 2. 0.]]
7
